### ISSUE TITLE
Anroid receives two push notifications instead of one

### ISSUE THREAD

**Issue by zabady** [timanrebel/Parse#10]
I am testing the app on Samsung galaxy s3, and samsung tablet, when I send a notification from the dashboard, the app receives two notifications instead of one, how can I solve that ?

I deleted the app, unsbscribed from channels and then subscribed in just one channel but same result.

**Comment by timanrebel** [comment]
Did you add anything to your `trap.xml` regarding Parse yourself? Because the module should do that all for you

**Comment by zabady** [comment]
I just added parse appId and clientKey properties in 'tiapp.xml' ...
Did you mean 'tiapp.xml' or 'trap.xml' ?

**Comment by timanrebel** [comment]
Sorry, `tiapp.xml` indeed (autocorrect). The AppId and ClientKey are indeed the only one that need to be added. Let me check if I have this issue as well with the latest version

**Comment by zabady** [comment]
Ok, thanks a lot for the quick response.
