### ISSUE TITLE
App crashes on android when a click on the notification happens

### ISSUE THREAD

**Issue by zabady** [timanrebel/Parse#11]
The app crashes on android when data has value,

`var data = Ti.App.Android.launchIntent.getStringExtra('com.parse.Data');`

When the app is closed and I click on the received notification, the app opens and but crashes in the previous line of code, am I doing something wrong ?

**Comment by luisestudioalfa** [comment]
Hi, did you solve it? I'm trying to show an alert message when i click on the received notification ( and the app in closed or in background), but i can't get the data of the notification.

How do i access it?

in my code i have 

Parse.addEventListener('notificationopen', function(e) {
    Ti.API.info("Parse notification open data: ", JSON.stringify(e));

    var data = Ti.App.Android.launchIntent.getStringExtra('com.parse.Data');
    Ti.API.info("Parse notification data: ", data);
});

but there is no mention in the logs to the passed data of the notification.

Thank you.
