### ISSUE TITLE
Android: Need to have access to the installation information

### ISSUE THREAD

**Issue by sfeather** [timanrebel/Parse#12]
Need to be able to query what channels a user is already subscribed to and in order to do that, need the installation objectId or the token.

**Comment by timanrebel** [comment]
Fair point, will add it asap!

**Comment by jasonkneen** [comment]
any idea when this will be added?

**Comment by timanrebel** [comment]
Let me try and add it this week! Should't be that hard

**Comment by timanrebel** [comment]
@jvandijk just did a PR that should fix it. My apologies for not doing it sooner

**Comment by jasonkneen** [comment]
Awesome
