### ISSUE TITLE
No notification received if force close app

### ISSUE THREAD

**Issue by mattberg** [timanrebel/Parse#15]
This module has worked perfectly for both when I open the app, and then close it and let it run in the background.

However, if I force close the app, then send a notification via Parse, I don't even receive the notification in the status bar. Any thoughts?

**Comment by timanrebel** [comment]
That is Android unfortunately. If you force close and app, it will not receive notifications until the user starts the app again. I understand why, but for developers it might be annoying. 

https://groups.google.com/forum/#!msg/android-gcm/MqVlA3Sj26c/uO-ttsXOyy0J

**Comment by mattberg** [comment]
Thank you for the quick reply. Makes sense. Do you know the best way then to test the scenario to get the app to not be running, basically where the following code would need to be used?

Ti.App.Android.launchIntent.getStringExtra('com.parse.Data')

I would also like to add that I am very thankful for this module. I have been using the REST API for iOS, but I am 1.5 years behind on getting push up for Android on my app. I was able to implement this in one evening. Any plans on finishing up the iOS version?

Do you have a donation page?

**Comment by timanrebel** [comment]
I'm still using the REST API for both iOS and Android for the data part. iOS also does not need a module for push, you can just push the device token to Parse via their REST API. At least, that's how I do it.

I don't have a donation's page, a thank you is all I need! All my open source projects are for personal use first and I try to open source everything that is not my core business. That way we all benefit

**Comment by mattberg** [comment]
Yeah, I am doing the same for iOS Push, just using their REST API with the token. The main benefit I would think would be nice on iOS is to have easier ways to manage the badges, and also to get the analytics of the push opens.

But again thank you, I will likely have my app updated on Android tonight.

**Comment by timanrebel** [comment]
good point! I might build an iOS version if I have some free time :)
