### ISSUE TITLE
Android, notification not showing when app is not started

### ISSUE THREAD

**Issue by tlenclos** [timanrebel/Parse#26]
When app is in front or background it works fine.
Maybe I'm missing something.

Any ideas ?

**Comment by timanrebel** [comment]
Do you force close the app? Because then Android will not allow the pp to receive notifications

**Comment by tlenclos** [comment]
Not at all, do you confirm that I don't have to register on google cloud console and fill these credentials on parse.com ?

**Comment by tlenclos** [comment]
All right I see, my app was getting killed by the system and therefore the service was also killed. Thanks !
