### ISSUE TITLE
Please add tags

### ISSUE THREAD

**Issue by jvandijk** [timanrebel/Parse#30]
Hey @timanrebel,

I would PR it if I could... but this is something you really need to do. Please add the tags for:

0.8 : commit [fee777b3c5d3790f957a0573ec4a17d75f49cb99](https://github.com/timanrebel/Parse/commit/fee777b3c5d3790f957a0573ec4a17d75f49cb99)
0.9 : commit [0ee8b22a39479f3036c532f84859e55834de1287](https://github.com/timanrebel/Parse/commit/0ee8b22a39479f3036c532f84859e55834de1287)
0.10 : commit [a47c92ced638990aac620eb17a5a95922134df0c](https://github.com/timanrebel/Parse/commit/a47c92ced638990aac620eb17a5a95922134df0c)

Thank you!

**Comment by timanrebel** [comment]
I was just pulling all changes. What about I give you collaborator status? :)

**Comment by jvandijk** [comment]
Hahaha, that is also an option of course.

**Comment by timanrebel** [comment]
Do you add the tags? Or shall I add them?

**Comment by jvandijk** [comment]
I will... no worries.
