### ISSUE TITLE
Please update gittion

### ISSUE THREAD

**Issue by DouglasHennrich** [timanrebel/Parse#31]
I notice that you have update your module, which is great by the way, but when I install it through gittion install, I get the 0.9 version

Cheers

**Comment by jvandijk** [comment]
@FokkeZB can you see what is going on here? I can indeed confirm that gitt.io has indexed version 0.9 while version 0.10 has already been tagged.

**Comment by FokkeZB** [comment]
@jvandijk Fixed a bug where 0.10 was seen as 0.1 (which already existed).

Will be up to date in 24h

**Comment by FokkeZB** [comment]
@timanrebel go ahead and close

**Comment by jvandijk** [comment]
@DouglasHennrich as mentioned, the correct version will show up in 24 hours. Closing issue!

**Comment by DouglasHennrich** [comment]
Thank you guys!
