### ISSUE TITLE
Custom notification sound ?

### ISSUE THREAD

**Issue by Badi3** [timanrebel/Parse#36]
How can I play custom notification sound ?
where exactly to put the sound file ?

Thanks.

**Comment by inakiabt** [comment]
@ElSifi Here you have how send push notifications from Parse for play custom sounds: https://www.parse.com/questions/custom-sound-in-push-notifications

And here where to put the sound file:
http://docs.appcelerator.com/platform/latest/#!/guide/Sending_and_Scheduling_Push_Notifications-section-43298780_SendingandSchedulingPushNotifications-soundsNotificationSounds

**Comment by maroqueen** [comment]
can i change the sound for android in parse by any way

**Comment by ElSifi** [comment]
@maroqueen 
I couldn't do it finally, Parse didn't support it back then, I don't know if there are any news now.
